### ISSUE TITLE
`useModal` hook from the README not working

### ISSUE THREAD

**Issue by Kerumen** [wellyshen/react-cool-portal#199]
I'm trying to create a custom hook `useModal` as in the README.
But I think there is a problem in the dependencies from the `useCallback` hook because it's not working.

```javascript
const useModal = (options = {}) => {
  const { Portal, isShow, ...rest } = usePortal({
    ...options,
    defaultShow: false,
  });

  const Modal = useCallback(
    ({ children }) => (
      <Portal>
        <div class={`modal${isShow ? " modal-open" : ""}`} tabIndex={-1}>
          {children}
        </div>
      </Portal>
    ),
    [] // <- here
  );

  return { Modal, isShow, ...rest };
};
```

When I call `show`, the modal doesn't open.

I think we could put `isShow` in the dependency list to fix the problem.

**Comment by wellyshen** [comment]
@Kerumen You are right, we need the dependency. I have corrected it, thank you bro.
