### ISSUE TITLE
Empty default container appears on init

### ISSUE THREAD

**Issue by ppazuchowski** [wellyshen/react-cool-portal#202]
# Bug Report

## Describe the Bug

When I render component with this hook, I see in the DOM empty container. When I try to show it and then hide, container disappear as expected. The problem occurs only on init. I have initialised that hook with a  `defaultShow: false`.

## How to Reproduce

1. Go to https://codesandbox.io/s/kind-ride-6ux23?file=/src/App.js
2. Open devtools and inspect `#react-cool-portal`
3. See that container exists on init.

## Expected Behavior

Container should not be visible on init, when I set `defaultShow: false`

## Screenshots

Add screenshots to help explain your problem.

## Your Environment

- OS: macOs
- Browser: Chrome
- Version of react-cool-portal: v1.0.11

**Comment by wellyshen** [comment]
@ppazuchowski Thank you for reporting this bug :)

**Comment by ppazuchowski** [comment]
Thank you for quick response and fix issue :)
