### ISSUE TITLE
Animation not working while creating a custom hook

### ISSUE THREAD

**Issue by kariae** [wellyshen/react-cool-portal#275]
# Bug Report

## Describe the Bug
I followed the doc to create a custom hook, but I feel like the transition CSS property is not working

## How to Reproduce
[Here](https://codesandbox.io/s/useportal-animation-ffr7m) is a sandbox that reproduces the issue, I just copy/paste the code from the doc

## Expected Behavior

The show/hide functionality is working fine, it just missing the transition

## Your Environment

- OS: macOS
- Browser Chrome
- Version of react-cool-portal: 1.0.14

**Comment by wellyshen** [comment]
@kariae 

Seems the css transition is be cut off due to the `<Portal />` is re-created. Hmm... interested 🤔.
For now, I think we should only layout the children of the modal without transition or animate it. I'm thinking about the solution.

**Comment by kariae** [comment]
thank you @wellyshen I'll continue with the custom hook and try to find a solution from my side as well, cause I did find the exact same issue with another package, maybe it's related to portals behavior

**Comment by wellyshen** [comment]
@kariae The root cause is the `<Portal />` component is re-created in the custom hook, we can avoid it by pass the `isShow` from the component's props. [Here's the solution](https://codesandbox.io/s/useportal-custom-clnqz?file=/src/useModal.tsx).

**Comment by kariae** [comment]
Thank you @wellyshen, definitely helpful, I was thinking about the same thing but I did put the `isShow` in the second parameter of the `useCallback` but didn't help.

**Comment by wellyshen** [comment]
@kariae Yea, the CSS class need to be toggled by a internal state or external prop.
