### ISSUE TITLE
Documentation: tooltip/dropdown example

### ISSUE THREAD

**Issue by parkersweb** [wellyshen/react-cool-portal#348]
I've had a good look through the documentation - but I'm struggling to see how to best implement a tooltip/dropdown type feature where the contents of the portal need to be updated with position information from the click target. 

Would it be possible to include some pointers in the documentation?

Thanks so much!

**Comment by wellyshen** [comment]
@parkersweb We need to set the position for the tooltip/dropdown. Here's the [demo](https://codesandbox.io/s/useportal-tooltip-x4mlw?file=/src/App.tsx). You can read this [article](https://blog.logrocket.com/learn-react-portals-by-example/) to learn more.

**Comment by parkersweb** [comment]
@wellyshen - Ah - thanks so much - perfect :)
