### ISSUE TITLE
Swapping content in the portal closes it

### ISSUE THREAD

**Issue by Kerumen** [wellyshen/react-cool-portal#390]
# Bug Report

## Describe the Bug

When you swap content in a portal, the portal closes.

## How to Reproduce

- Create a portal with a button in it. This button should be replaced when another content when clicked.
- Click on the button, the portal closes.

## CodeSandbox Link

https://codesandbox.io/s/focused-wing-xsyqq

## Expected Behavior

The portal should stay opened.

## Your Environment

- OS: macOS
- Browser: Chrome
- Version of react-cool-portal: v1.0.20

## Additional Information

I tracked down the issue, the problem is [here](https://github.com/wellyshen/react-cool-portal/blob/951c75f95573ed241903930674d38a602250069e/src/createPortal.ts#L48). When this code is executed, the content is already replaced so the condition returns `true`.
I found a workaround with a `setTimeout` (shown in the CodeSandbox) but I think this should be solved in the library side.

**Comment by wellyshen** [comment]
@Kerumen Thank you for reporting this bug, I will fix it soon.

**Comment by wellyshen** [comment]
@Kerumen This issue should be fixed in [v1.0.22](https://github.com/wellyshen/react-cool-portal/releases/tag/v1.0.22).

**Comment by Kerumen** [comment]
@wellyshen Thanks for the quick fix. However this is not working for my use case. I adapted the CodeSandbox to demonstrate it. Most of the time, the `onClick` handler is not directly on the clicked node if it's an icon, a button with some text in it..

The similar library `react-useportal` is using [this](https://github.com/alex-cory/react-useportal/blob/b1efedbaab98b60f1d14b9fd8ca1e176007f664a/usePortal.ts) condition to check if we should trigger the callback. Maybe we could use some inspiration.

**Comment by wellyshen** [comment]
@Kerumen Oh I got your point, I will find a solution for it soon.

**Comment by Kerumen** [comment]
I've forked the `useModal` example of their README and tested, this works well: https://codesandbox.io/s/useportal-usemodal-forked-ze0ou

**Comment by wellyshen** [comment]
@Kerumen Here you are [v1.0.23](https://github.com/wellyshen/react-cool-portal/releases/tag/v1.0.23). Thank you for letting this package becomes more cooler.

**Comment by Kerumen** [comment]
@wellyshen Perfect this works like a charm!
