### ISSUE TITLE
Dont delete container, or provide a means to retain it

### ISSUE THREAD

**Issue by cameronbraid** [wellyshen/react-cool-portal#584]
I have a container that I use with `containerId`. However when the portal closes you delete the container element.  This breaks my app.

The reason I use a custom element is to apply a className to the container to have the portal content styled.

After closing the portal, your library deletes this container element, then when re-opening the portal it re-creates the element under the body which is in the wrong place

**Comment by cameronbraid** [comment]
Could a simple solution be that if containerid is not the default value then don't remove it ?

**Comment by cameronbraid** [comment]
Found a hack workaround, create my container with blank space as its innerHTML :)

**Comment by wellyshen** [comment]
@cameronbraid Okay, I will provide an option to turn off/on the functionality of deleting the container automatically.

**Comment by wellyshen** [comment]
@cameronbraid Here's a new `autoRemoveContainer` option in [v1.1.0](https://github.com/wellyshen/react-cool-portal/releases/tag/v1.1.0) for you.

**Comment by cameronbraid** [comment]
Thanks

**Comment by zning** [comment]
> @cameronbraid Here's a new `autoRemoveContainer` option in [v1.1.0](https://github.com/wellyshen/react-cool-portal/releases/tag/v1.1.0) for you.

I just tested today and autoRemoveContainer did't work for me, sadly
